export const teamData = [
  {
    teamName: 'McLaren',
    engine: 'Mercedes',
    wins: 198,
    poles: 171,
    fastestLaps: 181,
    driversChampionships: 12,
    constructorsChampionships: 9,
    previousNames: [],
    experience: 88,
    pitstopSkill: 85,
    tyreManagement: 90,
    reliability: 87,
    strategyFlexibility: 86,
    budgetCapAdjusted: 165,
    budgetUsage: 0.96,
    budgetPenaltyRisk: 0.01,
    budgetEfficiency: 91,
    driverDevelopment: 92,
    mechanicalDNFRisk: 0.08,
    techUpgradeRate: 89,
    teamCohesion: 90
  },
  {
    teamName: 'Red Bull',
    engine: 'Honda',
    wins: 124,
    poles: 107,
    fastestLaps: 100,
    driversChampionships: 6,
    constructorsChampionships: 8,
    previousNames: ['Stewart', 'Jaguar'],
    experience: 95,
    pitstopSkill: 95,
    tyreManagement: 94,
    reliability: 92,
    strategyFlexibility: 94,
    budgetCapAdjusted: 165,
    budgetUsage: 0.99,
    budgetPenaltyRisk: 0.03,
    budgetEfficiency: 88,
    driverDevelopment: 85,
    mechanicalDNFRisk: 0.05,
    techUpgradeRate: 96,
    teamCohesion: 87
  },
  {
    teamName: 'Mercedes',
    engine: 'Mercedes',
    wins: 130,
    poles: 142,
    fastestLaps: 111,
    driversChampionships: 9,
    constructorsChampionships: 8,
    previousNames: ['Tyrrell', 'BAR', 'Honda', 'Brawn'],
    experience: 93,
    pitstopSkill: 90,
    tyreManagement: 88,
    reliability: 90,
    strategyFlexibility: 91,
    budgetCapAdjusted: 165,
    budgetUsage: 0.97,
    budgetPenaltyRisk: 0.02,
    budgetEfficiency: 85,
    driverDevelopment: 84,
    mechanicalDNFRisk: 0.07,
    techUpgradeRate: 90,
    teamCohesion: 88
  },
  {
    teamName: 'Ferrari',
    engine: 'Ferrari',
    wins: 247,
    poles: 253,
    fastestLaps: 262,
    driversChampionships: 15,
    constructorsChampionships: 16,
    previousNames: [],
    experience: 96,
    pitstopSkill: 84,
    tyreManagement: 86,
    reliability: 85,
    strategyFlexibility: 82,
    budgetCapAdjusted: 165,
    budgetUsage: 0.98,
    budgetPenaltyRisk: 0.02,
    budgetEfficiency: 80,
    driverDevelopment: 78,
    mechanicalDNFRisk: 0.10,
    techUpgradeRate: 83,
    teamCohesion: 75
  },
  {
    teamName: 'Williams',
    engine: 'Mercedes',
    wins: 114,
    poles: 128,
    fastestLaps: 133,
    driversChampionships: 7,
    constructorsChampionships: 9,
    previousNames: [],
    experience: 80,
    pitstopSkill: 78,
    tyreManagement: 75,
    reliability: 76,
    strategyFlexibility: 70,
    budgetCapAdjusted: 165,
    budgetUsage: 0.91,
    budgetPenaltyRisk: 0.01,
    budgetEfficiency: 82,
    driverDevelopment: 83,
    mechanicalDNFRisk: 0.12,
    techUpgradeRate: 72,
    teamCohesion: 80
  },
  {
    teamName: 'Aston Martin',
    engine: 'Mercedes',
    wins: 0,
    poles: 0,
    fastestLaps: 3,
    driversChampionships: 0,
    constructorsChampionships: 0,
    previousNames: ['Jordan', 'Midland', 'Spyker', 'Force India', 'Racing Point'],
    experience: 82,
    pitstopSkill: 83,
    tyreManagement: 80,
    reliability: 81,
    strategyFlexibility: 78,
    budgetCapAdjusted: 165,
    budgetUsage: 0.94,
    budgetPenaltyRisk: 0.01,
    budgetEfficiency: 79,
    driverDevelopment: 76,
    mechanicalDNFRisk: 0.11,
    techUpgradeRate: 80,
    teamCohesion: 82
  },
  {
    teamName: 'Alpine',
    engine: 'Renault',
    wins: 1,
    poles: 0,
    fastestLaps: 1,
    driversChampionships: 0,
    constructorsChampionships: 0,
    previousNames: ['Toleman', 'Benetton', 'Reanult', 'Lotus', 'Renault'],
    experience: 85,
    pitstopSkill: 80,
    tyreManagement: 78,
    reliability: 79,
    strategyFlexibility: 76,
    budgetCapAdjusted: 165,
    budgetUsage: 0.93,
    budgetPenaltyRisk: 0.01,
    budgetEfficiency: 77,
    driverDevelopment: 74,
    mechanicalDNFRisk: 0.13,
    techUpgradeRate: 78,
    teamCohesion: 79
  },
  {
    teamName: 'Haas',
    engine: 'Ferrari',
    wins: 0,
    poles: 1,
    fastestLaps: 3,
    driversChampionships: 0,
    constructorsChampionships: 0,
    previousNames: [],
    experience: 70,
    pitstopSkill: 72,
    tyreManagement: 68,
    reliability: 65,
    strategyFlexibility: 60,
    budgetCapAdjusted: 165,
    budgetUsage: 0.89,
    budgetPenaltyRisk: 0.00,
    budgetEfficiency: 75,
    driverDevelopment: 66,
    mechanicalDNFRisk: 0.18,
    techUpgradeRate: 65,
    teamCohesion: 70
  },
  {
    teamName: 'Sauber',
    engine: 'Ferrari',
    wins: 1,
    poles: 1,
    fastestLaps: 7,
    driversChampionships: 0,
    constructorsChampionships: 0,
    previousNames: ['Sauber', 'BMW', 'Sauber', 'Alfa Romeo'],
    experience: 78,
    pitstopSkill: 75,
    tyreManagement: 74,
    reliability: 72,
    strategyFlexibility: 68,
    budgetCapAdjusted: 165,
    budgetUsage: 0.90,
    budgetPenaltyRisk: 0.00,
    budgetEfficiency: 76,
    driverDevelopment: 72,
    mechanicalDNFRisk: 0.14,
    techUpgradeRate: 70,
    teamCohesion: 74
  },
  {
    teamName: 'Racing Bulls',
    engine: 'Honda',
    wins: 2,
    poles: 1,
    fastestLaps: 4,   
    driversChampionships: 0,
    constructorsChampionships: 0,
    previousNames: ['Minardi', 'Toro Rosso', 'Alpha Tauri'],
    experience: 76,
    pitstopSkill: 77,
    tyreManagement: 73,
    reliability: 70,
    strategyFlexibility: 72,
    budgetCapAdjusted: 165,
    budgetUsage: 0.92,
    budgetPenaltyRisk: 0.01,
    budgetEfficiency: 74,
    driverDevelopment: 80,
    mechanicalDNFRisk: 0.15,
    techUpgradeRate: 73,
    teamCohesion: 78
  },
];

