export const calendarData = [
  {
    round: 1,
    grandPrix: 'Bahrain',
    country: 'Bahrain',
    circuit: 'Bahrain International Circuit',
    location: 'Sakhir',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'night'
  },
  {
    round: 2,
    grandPrix: 'Saudi Arabian',
    country: 'Saudi Arabia',
    circuit: 'Jeddah Corniche Circuit',
    location: 'Jeddah',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 3,
    grandPrix: 'Australian',
    country: 'Australia',
    circuit: 'Albert Park Circuit',
    location: 'Melbourne',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 4,
    grandPrix: 'Japanese',
    country: 'Japan',
    circuit: 'Suzuka International Racing Course',
    location: 'Suzuka',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 2,
    grandPrix: '',
    country: '',
    circuit: '',
    location: '',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 2,
    grandPrix: '',
    country: '',
    circuit: '',
    location: '',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 2,
    grandPrix: '',
    country: '',
    circuit: '',
    location: '',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 2,
    grandPrix: '',
    country: '',
    circuit: '',
    location: '',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 2,
    grandPrix: '',
    country: '',
    circuit: '',
    location: '',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 2,
    grandPrix: '',
    country: '',
    circuit: '',
    location: '',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 2,
    grandPrix: '',
    country: '',
    circuit: '',
    location: '',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 2,
    grandPrix: '',
    country: '',
    circuit: '',
    location: '',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 2,
    grandPrix: '',
    country: '',
    circuit: '',
    location: '',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 2,
    grandPrix: '',
    country: '',
    circuit: '',
    location: '',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 2,
    grandPrix: '',
    country: '',
    circuit: '',
    location: '',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 2,
    grandPrix: '',
    country: '',
    circuit: '',
    location: '',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 2,
    grandPrix: '',
    country: '',
    circuit: '',
    location: '',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 2,
    grandPrix: '',
    country: '',
    circuit: '',
    location: '',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 2,
    grandPrix: '',
    country: '',
    circuit: '',
    location: '',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 2,
    grandPrix: '',
    country: '',
    circuit: '',
    location: '',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 2,
    grandPrix: '',
    country: '',
    circuit: '',
    location: '',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 2,
    grandPrix: '',
    country: '',
    circuit: '',
    location: '',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 2,
    grandPrix: '',
    country: '',
    circuit: '',
    location: '',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 2,
    grandPrix: '',
    country: '',
    circuit: '',
    location: '',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
]