export const calendarData = [
  {
    round: 1,
    grandPrix: 'Bahrain',
    country: 'Bahrain',
    circuit: 'Bahrain International Circuit',
    location: 'Sakhir',
    date: '02/03/2025',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'night'
  },
  {
    round: 2,
    grandPrix: 'Saudi Arabian',
    country: 'Saudi Arabia',
    circuit: 'Jeddah Corniche Circuit',
    location: 'Jeddah',
    date: '09/03/2025',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 3,
    grandPrix: 'Australian',
    country: 'Australia',
    circuit: 'Albert Park Circuit',
    location: 'Melbourne',
    date: '24/03/2025',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 4,
    grandPrix: 'Japanese',
    country: 'Japan',
    circuit: 'Suzuka International Racing Course',
    location: 'Suzuka',
    date: '07/04/2025',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 5,
    grandPrix: 'Chinese',
    country: 'China',
    circuit: 'Shanghai International Circuit',
    location: 'Shanghai',
    date: '21/04/2025',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 6,
    grandPrix: 'Miami',
    country: 'USA',
    circuit: 'Miami International Autodrome',
    location: 'Miami',
    date: '05/05/2025',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 7,
    grandPrix: 'Emilia Romagna',
    country: 'Italy',
    circuit: 'Imola Circuit',
    location: 'Imola',
    date: '19/05/2025',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 8,
    grandPrix: 'Monaco',
    country: 'Monaco',
    circuit: 'Circuit de Monaco',
    location: 'Monaco',
    date: '26/05/2025',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 9,
    grandPrix: 'Canadian',
    country: 'Canada',
    circuit: 'Circuit Gilles Villeneuve',
    location: 'Montreal',
    date: '09/06/2025',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 10,
    grandPrix: 'Spanish',
    country: 'Spain',
    circuit: 'Circuit de Barcelona-Catalunya',
    location: 'Montmeló',
    date: '23/06/2025',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 11,
    grandPrix: 'Austrian',
    country: 'Austria',
    circuit: 'Red Bull Ring',
    location: 'Spielberg',
    date: '30/06/2025',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 12,
    grandPrix: 'British',
    country: 'Britain',
    circuit: 'Silverstone Circuit',
    location: 'Silverstone',
    date: '07/07/2025',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 13,
    grandPrix: 'Hungarian',
    country: 'Hungary',
    circuit: 'Hungaroring',
    location: 'Mogyoród',
    date: '21/07/2025',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 14,
    grandPrix: 'Belgian',
    country: 'Belgium',
    circuit: 'Circuit de Spa-Francorchamps',
    location: 'Stavelot',
    date: '28/07/2025',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 15,
    grandPrix: 'Dutch',
    country: 'Netherlands',
    circuit: 'Circuit Zandvoort',
    location: 'Zandvoort',
    date: '25/08/2025',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 16,
    grandPrix: 'Italian',
    country: 'Italy',
    circuit: 'Monza Circuit',
    location: 'Monza',
    date: '01/09/2025',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 17,
    grandPrix: 'Azerbaijan',
    country: 'Azerbaijan',
    circuit: 'Baku City Circuit',
    location: 'Baku',
    date: '15/09/2025',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 18,
    grandPrix: 'Singapore',
    country: 'Singapore',
    circuit: 'Marina Bay Street Circuit',
    location: 'Singapore',
    date: '22/09/2025',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 19,
    grandPrix: 'United States',
    country: 'USA',
    circuit: 'Circuit of the Americas',
    location: 'Austin',
    date: '20/10/2025',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 20,
    grandPrix: 'Mexico City',
    country: 'Mexico',
    circuit: 'Autódromo Hermanos Rodríguez',
    location: 'Mexico City',
    date: '27/10/2025',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 2,
    grandPrix: '',
    country: '',
    circuit: '',
    location: '',
    date: '02/03/2025',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 2,
    grandPrix: '',
    country: '',
    circuit: '',
    location: '',
    date: '02/03/2025',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 2,
    grandPrix: '',
    country: '',
    circuit: '',
    location: '',
    date: '02/03/2025',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
  {
    round: 2,
    grandPrix: '',
    country: '',
    circuit: '',
    location: '',
    date: '02/03/2025',
    trackLengthKm: 5.412,
    laps: 57,
    sprintRace: false,
    wetRacePredictor: 0.01,
    raceTimeType: 'day'
  },
]