export const driverData = [
  {
    id: 1,
    firstname: 'Max',
    lastname: 'Verstappen',
    shortName: 'VER',
    carNumber: 33,
    team: 'Red Bull',
    nationality: 'Dutch',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 221,
    wins: 65,
    poles: 44,
    fastestLaps: 34,
    podiums: 117,
    points: 3188.5,
    worldChampionships: [
      2021, 2022, 2023, 2024
    ],
    coreSkill: 99,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 2,
    firstname: 'Yuki',
    lastname: 'Tsunoda',
    shortName: 'TSU',
    carNumber: 22,
    team: 'Red Bull',
    nationality: 'Japanese',
    dateOfBirth: '11/05/2000',
    grandPrixStarts: 99,
    wins: 0,
    poles: 0,
    fastestLaps: 1,
    podiums: 0,
    points: 101,
    worldChampionships: [],
    coreSkill: 72,
    wetWeatherMod: 0.058,
    tyreManagementMod: 0.068,
    reliabilityMod: 0.068
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
]