export const driverData = [
  {
    id: 1,
    firstname: 'Max',
    lastname: 'Verstappen',
    shortName: 'VER',
    carNumber: 33,
    team: 'Red Bull',
    nationality: 'Dutch',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 221,
    wins: 65,
    poles: 44,
    fastestLaps: 34,
    podiums: 117,
    points: 3188.5,
    worldChampionships: [
      2021, 2022, 2023, 2024
    ],
    coreSkill: 99,
    coreExperience: 89,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 2,
    firstname: 'Yuki',
    lastname: 'Tsunoda',
    shortName: 'TSU',
    carNumber: 22,
    team: 'Red Bull',
    nationality: 'Japanese',
    dateOfBirth: '11/05/2000',
    grandPrixStarts: 99,
    wins: 0,
    poles: 0,
    fastestLaps: 1,
    podiums: 0,
    points: 101,
    worldChampionships: [],
    coreSkill: 72,
    coreExperience: 76,
    wetWeatherMod: 0.058,
    tyreManagementMod: 0.068,
    reliabilityMod: 0.068
  },
  {
    id: 3,
    firstname: 'Lando',
    lastname: 'Norris',
    shortName: 'NOR',
    carNumber: 4,
    team: 'McLaren',
    nationality: 'British',
    dateOfBirth: '13/11/1999',
    grandPrixStarts: 140,
    wins: 8,
    poles: 12,
    fastestLaps: 17,
    podiums: 36,
    points: 1233,
    worldChampionships: [],
    coreSkill: 99,
    coreExperience: 75,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.096,
    reliabilityMod: 0.095
  },
  {
    id: 4,
    firstname: 'Oscar',
    lastname: 'Piastri',
    shortName: 'PIA',
    carNumber: 81,
    team: 'McLaren',
    nationality: 'Australian',
    dateOfBirth: '06/04/2001',
    grandPrixStarts: 58,
    wins: 7,
    poles: 4,
    fastestLaps: 7,
    podiums: 20,
    points: 623,
    worldChampionships: [],
    coreSkill: 93,
    coreExperience: 70,
    wetWeatherMod: 0.092,
    tyreManagementMod: 0.094,
    reliabilityMod: 0.096
  },
  {
    id: 5,
    firstname: 'George',
    lastname: 'Russell',
    shortName: 'RUS',
    carNumber: 63,
    team: 'Mercedes',
    nationality: 'British',
    dateOfBirth: '15/02/1998',
    grandPrixStarts: 140,
    wins: 4,
    poles: 6,
    fastestLaps: 9,
    podiums: 20,
    points: 861,
    worldChampionships: [],
    coreSkill: 87,
    coreExperience: 75,
    wetWeatherMod: 0.075,
    tyreManagementMod: 0.084,
    reliabilityMod: 0.084
  },
  {
    id: 6,
    firstname: 'Andrea Kimi',
    lastname: 'Antonelli',
    shortName: 'ANT',
    carNumber: 12,
    team: 'Mercedes',
    nationality: 'Italian',
    dateOfBirth: '25/08/2006',
    grandPrixStarts: 12,
    wins: 0,
    poles: 0,
    fastestLaps: 1,
    podiums: 1,
    points: 63,
    worldChampionships: [],
    coreSkill: 68,
    coreExperience: 60,
    wetWeatherMod: 0.045,
    tyreManagementMod: 0.060,
    reliabilityMod: 0.070
  },
  {
    id: 7,
    firstname: 'Lewis',
    lastname: 'Hamilton',
    shortName: 'HAM',
    carNumber: 44,
    team: 'Ferrari',
    nationality: 'British',
    dateOfBirth: '07/01/1985',
    grandPrixStarts: 368,
    wins: 105,
    poles: 104,
    fastestLaps: 67,
    podiums: 202,
    points: 4965.5,
    worldChampionships: [
      2008, 2014, 2015, 2017, 2018, 2019, 2020
    ],
    coreSkill: 89,
    coreExperience: 98,
    wetWeatherMod: 0.082,
    tyreManagementMod: 0.089,
    reliabilityMod: 0.089
  },
  {
    id: 8,
    firstname: 'Charles',
    lastname: 'Lerclerc',
    shortName: 'LEC',
    carNumber: 16,
    team: 'Ferrari',
    nationality: 'Monégasque',
    dateOfBirth: '16/10/1997',
    grandPrixStarts: 159,
    wins: 8,
    poles: 26,
    fastestLaps: 10,
    podiums: 47,
    points: 1549,
    worldChampionships: [],
    coreSkill: 91,
    coreExperience: 84,
    wetWeatherMod: 0.078,
    tyreManagementMod: 0.086,
    reliabilityMod: 0.086
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    coreExperience: 89,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    coreExperience: 89,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    coreExperience: 89,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    coreExperience: 89,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    coreExperience: 89,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    coreExperience: 89,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    coreExperience: 89,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    coreExperience: 89,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    coreExperience: 89,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    coreExperience: 89,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    coreExperience: 89,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    coreExperience: 89,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
]