export const driverData = [
  {
    id: 1,
    firstname: 'Max',
    lastname: 'Verstappen',
    shortName: 'VER',
    carNumber: 33,
    team: 'Red Bull',
    nationality: 'Dutch',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 221,
    wins: 65,
    poles: 44,
    fastestLaps: 34,
    podiums: 117,
    points: 3188.5,
    worldChampionships: [
      2021, 2022, 2023, 2024
    ],
    coreSkill: 99,
    coreExperience: 89,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 2,
    firstname: 'Yuki',
    lastname: 'Tsunoda',
    shortName: 'TSU',
    carNumber: 22,
    team: 'Red Bull',
    nationality: 'Japanese',
    dateOfBirth: '11/05/2000',
    grandPrixStarts: 99,
    wins: 0,
    poles: 0,
    fastestLaps: 1,
    podiums: 0,
    points: 101,
    worldChampionships: [],
    coreSkill: 72,
    coreExperience: 76,
    wetWeatherMod: 0.058,
    tyreManagementMod: 0.068,
    reliabilityMod: 0.068
  },
  {
    id: 3,
    firstname: 'Lando',
    lastname: 'Norris',
    shortName: 'NOR',
    carNumber: 4,
    team: 'McLaren',
    nationality: 'British',
    dateOfBirth: '13/11/1999',
    grandPrixStarts: 140,
    wins: 8,
    poles: 12,
    fastestLaps: 17,
    podiums: 36,
    points: 1233,
    worldChampionships: [],
    coreSkill: 99,
    coreExperience: 83,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.096,
    reliabilityMod: 0.095
  },
  {
    id: 4,
    firstname: 'Oscar',
    lastname: 'Piastri',
    shortName: 'PIA',
    carNumber: 81,
    team: 'McLaren',
    nationality: 'Australian',
    dateOfBirth: '06/04/2001',
    grandPrixStarts: 58,
    wins: 7,
    poles: 4,
    fastestLaps: 7,
    podiums: 20,
    points: 623,
    worldChampionships: [],
    coreSkill: 93,
    coreExperience: 75,
    wetWeatherMod: 0.092,
    tyreManagementMod: 0.094,
    reliabilityMod: 0.096
  },
  {
    id: 5,
    firstname: 'George',
    lastname: 'Russell',
    shortName: 'RUS',
    carNumber: 63,
    team: 'Mercedes',
    nationality: 'British',
    dateOfBirth: '15/02/1998',
    grandPrixStarts: 140,
    wins: 4,
    poles: 6,
    fastestLaps: 9,
    podiums: 20,
    points: 861,
    worldChampionships: [],
    coreSkill: 87,
    coreExperience: 83,
    wetWeatherMod: 0.075,
    tyreManagementMod: 0.084,
    reliabilityMod: 0.084
  },
  {
    id: 6,
    firstname: 'Andrea Kimi',
    lastname: 'Antonelli',
    shortName: 'ANT',
    carNumber: 12,
    team: 'Mercedes',
    nationality: 'Italian',
    dateOfBirth: '25/08/2006',
    grandPrixStarts: 12,
    wins: 0,
    poles: 0,
    fastestLaps: 1,
    podiums: 1,
    points: 63,
    worldChampionships: [],
    coreSkill: 68,
    coreExperience: 60,
    wetWeatherMod: 0.045,
    tyreManagementMod: 0.060,
    reliabilityMod: 0.070
  },
  {
    id: 7,
    firstname: 'Lewis',
    lastname: 'Hamilton',
    shortName: 'HAM',
    carNumber: 44,
    team: 'Ferrari',
    nationality: 'British',
    dateOfBirth: '07/01/1985',
    grandPrixStarts: 368,
    wins: 105,
    poles: 104,
    fastestLaps: 67,
    podiums: 202,
    points: 4965.5,
    worldChampionships: [
      2008, 2014, 2015, 2017, 2018, 2019, 2020
    ],
    coreSkill: 89,
    coreExperience: 98,
    wetWeatherMod: 0.082,
    tyreManagementMod: 0.089,
    reliabilityMod: 0.089
  },
  {
    id: 8,
    firstname: 'Charles',
    lastname: 'Lerclerc',
    shortName: 'LEC',
    carNumber: 16,
    team: 'Ferrari',
    nationality: 'Monégasque',
    dateOfBirth: '16/10/1997',
    grandPrixStarts: 159,
    wins: 8,
    poles: 26,
    fastestLaps: 10,
    podiums: 47,
    points: 1549,
    worldChampionships: [],
    coreSkill: 91,
    coreExperience: 84,
    wetWeatherMod: 0.078,
    tyreManagementMod: 0.086,
    reliabilityMod: 0.086
  },
  {
    id: 9,
    firstname: 'Fernando',
    lastname: 'Alonso',
    shortName: 'ALO',
    carNumber: 14,
    team: 'Aston Martin',
    nationality: 'Spanish',
    dateOfBirth: '29/07/1981',
    grandPrixStarts: 413,
    wins: 32,
    poles: 22,
    fastestLaps: 26,
    podiums: 106,
    points: 2353,
    worldChampionships: [
      2005, 2006
    ],
    coreSkill: 84,
    coreExperience: 99,
    wetWeatherMod: 0.090,
    tyreManagementMod: 0.088,
    reliabilityMod: 0.088
  },
  {
    id: 10,
    firstname: 'Lance',
    lastname: 'Stroll',
    shortName: 'STR',
    carNumber: 18,
    team: 'Aston Martin',
    nationality: 'Canadian',
    dateOfBirth: '29/10/1998',
    grandPrixStarts: 177,
    wins: 0,
    poles: 1,
    fastestLaps: 0,
    podiums: 3,
    points: 312,
    worldChampionships: [],
    coreSkill: 74,
    coreExperience: 78,
    wetWeatherMod: 0.068,
    tyreManagementMod: 0.074,
    reliabilityMod: 0.076
  },
  {
    id: 11,
    firstname: 'Carlos',
    lastname: 'Sainz',
    shortName: 'SAI',
    carNumber: 55,
    team: 'Williams',
    nationality: 'Spanish',
    dateOfBirth: '01/09/1994',
    grandPrixStarts: 217,
    wins: 4,
    poles: 6,
    fastestLaps: 4,
    podiums: 27,
    points: 1285.5,
    worldChampionships: [],
    coreSkill: 85,
    coreExperience: 90,
    wetWeatherMod: 0.080,
    tyreManagementMod: 0.091,
    reliabilityMod: 0.090
  },
  {
    id: 12,
    firstname: 'Alex',
    lastname: 'Albon',
    shortName: 'ALB',
    carNumber: 23,
    team: 'Williams',
    nationality: 'Thai',
    dateOfBirth: '23/03/1996',
    grandPrixStarts: 116,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 2,
    points: 286,
    worldChampionships: [],
    coreSkill: 78,
    coreExperience: 80,
    wetWeatherMod: 0.070,
    tyreManagementMod: 0.078,
    reliabilityMod: 0.080
  },
  {
    id: 14,
    firstname: 'Pierre',
    lastname: 'Gasly',
    shortName: 'GAS',
    carNumber: 10,
    team: 'Alpine',
    nationality: 'French',
    dateOfBirth: '97/02/1996',
    grandPrixStarts: 165,
    wins: 1,
    poles: 0,
    fastestLaps: 3,
    podiums: 5,
    points: 455,
    worldChampionships: [],
    coreSkill: 80,
    coreExperience: 87,
    wetWeatherMod: 0.073,
    tyreManagementMod: 0.080,
    reliabilityMod: 0.082
  },
  {
    id: 15,
    firstname: 'Franco',
    lastname: 'Colapinto',
    shortName: 'COL',
    carNumber: 43,
    team: 'Alpine',
    nationality: 'Argentine',
    dateOfBirth: '27/05/2003',
    grandPrixStarts: 14,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 5,
    worldChampionships: [],
    coreSkill: 62,
    coreExperience: 54,
    wetWeatherMod: 0.038,
    tyreManagementMod: 0.054,
    reliabilityMod: 0.058
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    coreExperience: 89,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    coreExperience: 89,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    coreExperience: 89,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    coreExperience: 89,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    coreExperience: 89,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
  {
    id: 1,
    firstname: '',
    lastname: '',
    shortName: '',
    carNumber: 1,
    team: '',
    nationality: '',
    dateOfBirth: '30/09/1997',
    grandPrixStarts: 1,
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    podiums: 0,
    points: 0,
    worldChampionships: [],
    coreSkill: 99,
    coreExperience: 89,
    wetWeatherMod: 0.099,
    tyreManagementMod: 0.099,
    reliabilityMod: 0.099
  },
]