export const teamData = [
  {
    teamName: 'McLaren',
    engine: 'Mercedes',
    wins: 198,
    poles: 171,
    fastestLaps: 181,
    driversChampionships: 12,
    constructorsChampionships: 9,
    previousNames: [],
  },
  {
    teamName: 'Red Bull',
    engine: 'Honda',
    wins: 124,
    poles: 107,
    fastestLaps: 100,
    driversChampionships: 6,
    constructorsChampionships: 8,
    previousNames: ['Stewart', 'Jaguar'],
  },
  {
    teamName: 'Mercedes',
    engine: 'Mercedes',
    wins: 130,
    poles: 142,
    fastestLaps: 111,
    driversChampionships: 9,
    constructorsChampionships: 8,
    previousNames: ['Tyrrell', 'BAR', 'Honda', 'Brawn'],
  },
  {
    teamName: 'Ferrari',
    engine: 'Ferrari',
    wins: 247,
    poles: 253,
    fastestLaps: 262,
    driversChampionships: 15,
    constructorsChampionships: 16,
    previousNames: [],
  },
  {
    teamName: 'Williams',
    engine: 'Mercedes',
    wins: 114,
    poles: 128,
    fastestLaps: 133,
    driversChampionships: 7,
    constructorsChampionships: 9,
    previousNames: [],
  },
  {
    teamName: 'Aston Martin',
    engine: 'Mercedes',
    wins: 0,
    poles: 0,
    fastestLaps: 3,
    driversChampionships: 0,
    constructorsChampionships: 0,
    previousNames: ['Jordan', 'Midland', 'Spyker', 'Force India', 'Racing Point'],
  },
  {
    teamName: 'Alpine',
    engine: 'Renault',
    wins: 1,
    poles: 0,
    fastestLaps: 1,
    driversChampionships: 0,
    constructorsChampionships: 0,
    previousNames: ['Toleman', 'Benetton', 'Reanult', 'Lotus', 'Renault'],
  },
  {
    teamName: 'Haas',
    engine: 'Ferrari',
    wins: 0,
    poles: 1,
    fastestLaps: 3,
    driversChampionships: 0,
    constructorsChampionships: 0,
    previousNames: [],
  },
  {
    teamName: 'Sauber',
    engine: 'Ferrari',
    wins: 1,
    poles: 1,
    fastestLaps: 7,
    driversChampionships: 0,
    constructorsChampionships: 0,
    previousNames: ['Sauber', 'BMW', 'Sauber', 'Alfa Romeo'],
  },
  {
    teamName: 'Racing Bulls',
    engine: 'Honda',
    wins: 2,
    poles: 1,
    fastestLaps: 4,   
    driversChampionships: 0,
    constructorsChampionships: 0,
    previousNames: ['Minardi', 'Toro Rosso', 'Alpha Tauri'],
  },
];

