export const teamData = [
  {
    teamName: 'McLaren',
    engine: 'Mercedes',
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    driversChampionships: 0,
    constructorsChampionships: 0,
    previousNames: [],
  },
  {
    teamName: 'Red Bull',
    engine: 'Honda',
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    driversChampionships: 0,
    constructorsChampionships: 0,
    previousNames: [],
  },
  {
    teamName: 'Mercedes',
    engine: 'Mercedes',
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    driversChampionships: 0,
    constructorsChampionships: 0,
    previousNames: [],
  },
  {
    teamName: 'Ferrari',
    engine: 'Ferrari',
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    driversChampionships: 0,
    constructorsChampionships: 0,
    previousNames: [],
  },
  {
    teamName: 'Williams',
    engine: 'Mercedes',
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    driversChampionships: 0,
    constructorsChampionships: 0,
    previousNames: [],
  },
  {
    teamName: 'Aston Martin',
    engine: 'Mercedes',
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    driversChampionships: 0,
    constructorsChampionships: 0,
    previousNames: [],
  },
  {
    teamName: 'Alpine',
    engine: 'Renault',
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    driversChampionships: 0,
    constructorsChampionships: 0,
    previousNames: [],
  },
  {
    teamName: 'Haas',
    engine: 'Ferrari',
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    driversChampionships: 0,
    constructorsChampionships: 0,
    previousNames: [],
  },
  {
    teamName: 'Sauber',
    engine: 'Ferrari',
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    driversChampionships: 0,
    constructorsChampionships: 0,
    previousNames: [],
  },
  {
    teamName: 'Racing Bulls',
    engine: 'Honda',
    wins: 0,
    poles: 0,
    fastestLaps: 0,
    driversChampionships: 0,
    constructorsChampionships: 0,
    previousNames: [
      
    ],
  },
]