export const teamData = [
  {
    teamName: 'McLaren',
    engine: 'Mercedes',
    wins: 198,
    poles: 168,
    fastestLaps: 161,
    driversChampionships: 12,
    constructorsChampionships: 9,
    previousNames: [],
  },
  {
    teamName: 'Red Bull',
    engine: 'Honda',
    wins: 124,
    poles: 93,
    fastestLaps: 97,
    driversChampionships: 6,
    constructorsChampionships: 5,
    previousNames: ['Stewart', 'Jaguar'],
  },
  {
    teamName: 'Mercedes',
    engine: 'Mercedes',
    wins: 130,
    poles: 141,
    fastestLaps: 102,
    driversChampionships: 9,
    constructorsChampionships: 8,
    previousNames: ['Tyrrell', 'BAR', 'Honda', 'Brawn'],
  },
  {
    teamName: 'Ferrari',
    engine: 'Ferrari',
    wins: 248,
    poles: 253,
    fastestLaps: 259,
    driversChampionships: 15,
    constructorsChampionships: 16,
    previousNames: [],
  },
  {
    teamName: 'Williams',
    engine: 'Mercedes',
    wins: 114,
    poles: 128,
    fastestLaps: 133,
    driversChampionships: 7,
    constructorsChampionships: 9,
    previousNames: [],
  },
  {
    teamName: 'Aston Martin',
    engine: 'Mercedes',
    wins: 0,
    poles: 1,
    fastestLaps: 3,
    driversChampionships: 0,
    constructorsChampionships: 0,
    previousNames: ['Jordan', 'Midland', 'Spyker', 'Force India', 'Racing Point'],
  },
  {
    teamName: 'Alpine',
    engine: 'Renault',
    wins: 21,
    poles: 20,
    fastestLaps: 25,
    driversChampionships: 2,
    constructorsChampionships: 2,
    previousNames: ['Toleman', 'Benetton', 'Reanult', 'Lotus', 'Renault'],
  },
  {
    teamName: 'Haas',
    engine: 'Ferrari',
    wins: 0,
    poles: 1,
    fastestLaps: 3,
    driversChampionships: 0,
    constructorsChampionships: 0,
    previousNames: [],
  },
  {
    teamName: 'Sauber',
    engine: 'Ferrari',
    wins: 1,
    poles: 1,
    fastestLaps: 2,
    driversChampionships: 0,
    constructorsChampionships: 0,
    previousNames: ['BMW'],
  },
  {
    teamName: 'Racing Bulls',
    engine: 'Honda',
    wins: 1,
    poles: 1,
    fastestLaps: 2,
    driversChampionships: 0,
    constructorsChampionships: 0,
    previousNames: ['Minardi', 'Toro Rosso', 'Alpha Tauri'],
  },
];